<a href="https://colab.research.google.com/github/CodeRunner24/PyTorch/blob/main/PyTorch_Lesson_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.3.0+cu121


Introduction to tensors

Creating Tensors
Scalar

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
scalar.item()

7

Vector

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.shape

torch.Size([2])

MATRIX

In [ ]:
MATRIX = torch.tensor([[7,8],[9,6]])
MATRIX.ndim
MATRIX

tensor([[7, 8],
        [9, 6]])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[8,5,5],[4,9,2]]])
TENSOR

tensor([[[1, 2, 3],
         [8, 5, 5],
         [4, 9, 2]]])

In [ ]:
TENSOR.shape


torch.Size([1, 3, 3])

Random Tensors  

They are important beacuse NN learns from random numbers and adjust them to better represent the data.

Random- look at data- update random numbers - look at data - update random numbers

In [ ]:
# Creeating of random tensors of shape or size
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6055, 0.0682, 0.0983, 0.7407],
        [0.6296, 0.5965, 0.5437, 0.6639],
        [0.4951, 0.6704, 0.7824, 0.7080]])

In [ ]:
# Creation of a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,244,3)) #height, width, color(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 244, 3]), 3)

In [ ]:
# Zero and ones tensor
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# seeing the datatype
ones.dtype

torch.float32

Creating a Range of tensors


In [ ]:
# usage of torch.arange()
one_to_ten = torch.arange(start=0, end=302, step=4.5)
one_to_ten

tensor([  0.0000,   4.5000,   9.0000,  13.5000,  18.0000,  22.5000,  27.0000,
         31.5000,  36.0000,  40.5000,  45.0000,  49.5000,  54.0000,  58.5000,
         63.0000,  67.5000,  72.0000,  76.5000,  81.0000,  85.5000,  90.0000,
         94.5000,  99.0000, 103.5000, 108.0000, 112.5000, 117.0000, 121.5000,
        126.0000, 130.5000, 135.0000, 139.5000, 144.0000, 148.5000, 153.0000,
        157.5000, 162.0000, 166.5000, 171.0000, 175.5000, 180.0000, 184.5000,
        189.0000, 193.5000, 198.0000, 202.5000, 207.0000, 211.5000, 216.0000,
        220.5000, 225.0000, 229.5000, 234.0000, 238.5000, 243.0000, 247.5000,
        252.0000, 256.5000, 261.0000, 265.5000, 270.0000, 274.5000, 279.0000,
        283.5000, 288.0000, 292.5000, 297.0000, 301.5000])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Tensor Datatype (Important)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,
                               device = None,
                               requires_grad=False )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half) #half and float16 is the same thing in torch
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

Getting information from tensors

1. Tensors not right datatype - to do get "tensor.dtype"
2. Tensors not in right shae - to do get "tensor.shape"
3. Tensors not on the right device - to do get "tansor.device"

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7738, 0.1224, 0.4963, 0.5526],
        [0.1225, 0.9632, 0.7321, 0.3572],
        [0.7346, 0.3925, 0.0196, 0.1187]])

In [ ]:
# Finding out the details about the tensor
print(some_tensor)
print(some_tensor.dtype)
print(some_tensor.shape)
print(some_tensor.device)

tensor([[0.7738, 0.1224, 0.4963, 0.5526],
        [0.1225, 0.9632, 0.7321, 0.3572],
        [0.7346, 0.3925, 0.0196, 0.1187]])
torch.float32
torch.Size([3, 4])
cpu


### Manipulating  Tensors

Tensor operations include:

* Addititon
* Substraction
* Multiplication
* Division
* Matrix multiplicaiton

In [ ]:
# Create a tensor
tensor = torch.tensor([1,2,3])
print(tensor + 10)
print(tensor*10)
print(tensor/10)


tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# Pytorch in-built Funcstions

torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multiplication

Two main ways of doing,

1. Element-wise
2. Matrix Multiplication (most common one in deep learning - dot product)

Note: there are 2 main rules to be satisfied for matrix mul,
  1. The **inner dimensions** must match just like in math
  2. The resulting matrix has the shape of **outer dimensions**


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix wise multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2+ 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]* tensor[i]
print(value)

tensor(14)
CPU times: user 1.79 ms, sys: 43 µs, total: 1.83 ms
Wall time: 3.5 ms


In [ ]:
%%time
print(torch.matmul(tensor, tensor)) # so it is much more faster than math version

tensor(14)
CPU times: user 497 µs, sys: 0 ns, total: 497 µs
Wall time: 507 µs


### Shape Error when Multiplication (most common in deep learning)

In [ ]:
# Shapes for matrix multiplication

tensorA = torch.tensor([[1,2],
                       [3,4],
                       [5,6]])

tensorB = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

torch.mm(tensorA, tensorB) #tensor mm is the same with torch.matmul


### To fix our tensor shape error we can change the shape of using **transpose** using .T

In [ ]:
tensorB.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
torch.mm(tensorA, tensorB.T) # correct version

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc (Tensor Aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Finding the min
torch.min(x) # or
x.min()

# Finding the max
torch.max(x) # or
x.max()

# Finding the mean
torch.mean(x.type(torch.float32)) # or
x.type(torch.float32).mean()

# Finding the sum
torch.sum(x) # or
x.sum()

tensor(450)

### Finding thge position of min and max using indexes

In [ ]:
# Finding the position in the tensor min argmin
x.argmin()

# Finding the position in the tensor max using argmax
x.argmax()

tensor(9)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Rehsaping: reshpaes input
* View: Return a view of an input tensor but keeps the original
* Stacking: combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze: removes all "1" dimensions from a tensor
* Squeeze: add all "1" dimensions to a target tensor
* Permute: return a view of an input with dimensions swapped in a certain way



In [ ]:
# Create a tensor
import torch
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension with reshape
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x because a view of tensor shares the same memory as the original one
z[:, 0] = 6
z,x

(tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x

tensor([6., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Stack tensors on top on each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.],
        [6., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Unsqeeze by using torch.unsqueeze(): adds an extra dimension to a tensor
x_reshaped.squeeze().unsqueeze(dim=0), x_reshaped.squeeze().unsqueeze(dim=0).shape

(tensor([[6., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Permute: to rearrange the dimension of a tensor
# Let's create an image:
x_original = torch.rand(size=(224,224,3)) # size=(height,width,color)


# Permute the original tensor:
x_permuted = x_original.permute(2,0,1) # dim, height, width
x_original.shape,  x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

# Indexing:

#### Indexing is selecting data from tensors


In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's use different indices on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# Can also use ":" to select all of a target dimension
x[:, 0],x[:, 1],x[:, 2]

(tensor([[1, 2, 3]]), tensor([[4, 5, 6]]), tensor([[7, 8, 9]]))

In [ ]:
# Can also use ":" to select all but only index 1 of 2'nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

## PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> 'torch.from_numpy(ndarray)'
* PyTorch tensor -> NumPy -> "torch.Tensor.numpy"

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy to pytorch, pytorch reflects numpy's datatype of float64.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability (trying to take random out of random)

In short, how a naural network learns:

"Start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data and continue..."

To reduce the randomness in neural newtworks comes the concept of **random seed**.

Seed does is "flavour" the randomness

In [ ]:
import torch

# Create 2 random tensors
randtA = torch.rand(3,4)
randtB = torch.rand(3,4)

print(randtA == randtB)

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make reproducable tensors
import torch

# Set the random **seed**
# To make them same everytime the random torch created
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
randtC = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
randtD = torch.rand(3,4)

print(randtC)
print(randtD)
print(randtC == randtD)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch Objects on the GPU to make faster computations

#### GPU = faster computation on numbers

### Getting a GPU

1. Easiest - Use Google Colab Pro to get GPU
2. Use your own GPU(which i did already)

In [ ]:
!nvidia-smi

Sun May 26 16:17:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## 2. Check for GPU Access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

# 3. Putting tensors and models on the GPU

####The reason is we want our tensors and models on the GPU to be faster

In [19]:
# Create a tensor (default on the CPU)
import torch
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move to GPU and print
GPU_tensor = tensor.to(device)
print(GPU_tensor, GPU_tensor.device)

# Move to CPU again(for fun only)
CPU_tensor = tensor.to(tensor.device)
print(CPU_tensor, CPU_tensor.device)

tensor([1, 2, 3]) cpu
tensor([1, 2, 3], device='cuda:0') cuda:0
tensor([1, 2, 3]) cpu


## Exercises and Extras

### See Exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises